export const schemaSQL = `
CREATE TABLE IF NOT EXISTS UserSettings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  dailyAllowance INTEGER NOT NULL DEFAULT 50000,
  maxWalletCap INTEGER NOT NULL DEFAULT 0,
  lastRolloverAt TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS TokenWallet (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  balance INTEGER NOT NULL DEFAULT 0,
  usedToday INTEGER NOT NULL DEFAULT 0,
  savedTotal INTEGER NOT NULL DEFAULT 0,
  updatedAt TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL,
  tokens INTEGER NOT NULL,
  metadata TEXT,
  createdAt TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Chats (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  createdAt TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Messages (
  id TEXT PRIMARY KEY,
  chatId TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  inputTokens INTEGER DEFAULT 0,
  outputTokens INTEGER DEFAULT 0,
  createdAt TEXT NOT NULL,
  FOREIGN KEY (chatId) REFERENCES Chats(id)
);
CREATE TABLE IF NOT EXISTS UsageAnalytics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day TEXT NOT NULL,
  inputTokens INTEGER NOT NULL,
  outputTokens INTEGER NOT NULL,
  totalTokens INTEGER NOT NULL,
  estimatedCostUSD REAL NOT NULL
);
`;
